from __future__ import annotations

from typing import Any, Dict, Iterator, List, Mapping, Optional, Protocol, Sequence

from src.core.contracts import ChildChunk, DocumentVersion, IngestionTask, ParentChunk, Vector


Candidate = Dict[str, Any]
Triple = Dict[str, Any]


class ObjectStorage(Protocol):
    def put_bytes(self, uri: str, data: bytes, content_type: str) -> None: ...
    def exists(self, uri: str) -> bool: ...
    def read_bytes(self, uri: str) -> bytes: ...
    def delete(self, uri: str) -> None: ...


class DocumentRepository(Protocol):
    def save(self, version: DocumentVersion) -> None: ...
    def get_latest(self, document_id: str) -> Optional[DocumentVersion]: ...
    def delete(self, document_id: str) -> None: ...


class TaskRepository(Protocol):
    def save(self, task: IngestionTask) -> None: ...
    def get(self, task_id: str) -> Optional[IngestionTask]: ...
    def get_latest_for_document(self, document_id: str) -> Optional[IngestionTask]: ...


class ReadinessProbe(Protocol):
    name: str
    required: bool
    def check(self) -> bool: ...


class QueueOperations(Protocol):
    def submit_task(self, file_path: str) -> str: ...
    def get_task_status(self, task_id: str) -> Optional[Dict[str, Any]]: ...


class DocumentChunker(Protocol):
    def process_file(self, file_path: str, document_id: str) -> tuple[List[ParentChunk], List[ChildChunk]]: ...


class DenseIndex(Protocol):
    def upsert_chunks_bulk(self, chunks: List[ChildChunk], embeddings: List[Vector]) -> None: ...
    def search_similar(
        self, query_vector: Vector, limit: int = 3, metadata_filter: Optional[Dict[str, Any]] = None
    ) -> List[Candidate]: ...
    def delete_document(self, document_id: str) -> None: ...


class SparseIndex(Protocol):
    def add_documents(self, chunks: List[ChildChunk]) -> None: ...
    def search(
        self, query: str, top_k: int = 10, metadata_filter: Optional[Dict[str, Any]] = None
    ) -> List[Candidate]: ...
    def get_by_chunk_or_parent(self, identifier: str) -> List[Candidate]: ...
    def delete_document(self, document_id: str) -> List[str]: ...


class GraphIndex(Protocol):
    def add_triples_bulk(self, triples: List[Triple], chunk_id: Optional[str] = None) -> None: ...
    def traverse_graph_hops(self, seed_entities: List[str], max_hops: int = 1) -> List[Candidate]: ...
    def delete_document(self, document_id: str) -> None: ...


class EmbeddingProvider(Protocol):
    vector_dim: int
    def get_embeddings_batched(self, texts: List[str], batch_size: int = 64) -> List[Vector]: ...


class RerankingProvider(Protocol):
    def predict(self, pairs: Sequence[Sequence[str]]) -> Any: ...


class QueryProcessor(Protocol):
    def process_query(self, raw_query: str) -> Mapping[str, str]: ...


class AnswerGenerator(Protocol):
    def generate_stream(
        self, query: str, context_pool: List[Candidate], score_threshold: float = -2.0
    ) -> Iterator[str]: ...


class GraphExtractionProvider(Protocol):
    def extract_triples(self, text: str) -> List[Triple]: ...


class CacheProvider(Protocol):
    def get(self, key: str) -> Optional[Vector]: ...
    def set(self, key: str, value: Vector) -> None: ...


class Retriever(Protocol):
    def retrieve(
        self,
        query: str,
        top_k: int = 10,
        filters: Optional[Dict[str, Any]] = None,
        context: Optional[Dict[str, Any]] = None,
    ) -> List[Candidate]: ...


class FusionStrategy(Protocol):
    def fuse(self, ranked_lists: List[List[Candidate]]) -> List[Candidate]: ...
